config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('memo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

memo/urls.py
from django.urls import path

from .views import (
    MemoList, MemoDetail, MemoCreate, MemoDelete, MemoUpdate, MemoListAPI, MemoRetirieveAPI, MemoCreateAPI, MemoUpdateAPI, MemoDestroyAPI,
)

app_name = 'memo'
urlpatterns = [
    path('', MemoList.as_view(), name='index'),
    path('new_memo', MemoCreate.as_view(), name='new_memo'),
    path('detail/<slug:slug>', MemoDetail.as_view(), name='detail'),
    path('delete/<slug:slug>', MemoDelete.as_view(), name='delete_memo'),
    path('edit/<slug:slug>', MemoUpdate.as_view(), name='edit_memo'),
    path('api/memos/', MemoListAPI.as_view(), name='api_list'),
    path('api/memos/detail/<slug:slug>/', MemoRetirieveAPI.as_view(), name='api_retrieve'),
    path('api/memos/new/', MemoCreateAPI.as_view(), name='api_create'),
    path('api/memos/edit/<slug:slug>/', MemoUpdateAPI.as_view(), name='api_update'),
    path('api/memos/delete/<slug:slug>/', MemoDestroyAPI.as_view(), name='api_delete'),
]

memo/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class Author(AbstractUser):
    pass


class Memo(models.Model):
    title = models.CharField('タイトル', max_length=150)
    slug = models.SlugField('スラッグ', unique=True)
    text = models.TextField('本文', blank=True)
    created_datetime = models.DateTimeField('作成日時', auto_now_add=True)
    updated_datetime = models.DateTimeField('更新日時', auto_now=True)

    class Meta:
        ordering = ('-created_datetime',)

    def __str__(self):
        return self.title

memo/forms.py
from django import forms
from django.db.models import Q

from .models import Memo


class MemoForm(forms.ModelForm):
    title = forms.CharField(
        label='タイトル',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'タイトル'
        }),
    )
    slug = forms.CharField(
        label='スラッグ',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'スラッグ'
        })
    )
    text = forms.CharField(
        label='本文',
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': '本文'
        })
    )

    class Meta:
        model = Memo
        fields = ('title', 'slug', 'text')


class MemoSearchForm(forms.Form):
    keyword = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={
            'class': 'form-control mr-sm-2',
            'placeholder': 'メモを検索'
        }),
        required=False,
    )

    def filter_memos(self, memos):
        if self.is_valid():
            keyword = self.cleaned_data.get('keyword')
            if keyword:
                memos = memos.filter(
                    Q(title__icontains=keyword) | Q(text__icontains=keyword)
                )

        return memos

memo/views.py
from django.shortcuts import resolve_url
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, DetailView, CreateView, DeleteView, UpdateView,
)
from rest_framework.generics import (
    ListAPIView, RetrieveAPIView, CreateAPIView, UpdateAPIView, DestroyAPIView,
)

from .forms import MemoForm, MemoSearchForm
from .models import Memo
from .serializers import (
    MemoListSerializer, MemoRetrieveSerializer, MemoCreateSerializer, MemoUpdateSerializer, MemoDestroySerializer,
)

# Create your views here.

class MemoList(ListView):
    model = Memo
    template_name = 'memo/index.html'
    paginate_by = 10

    def get_queryset(self):
        form = MemoSearchForm(self.request.GET)
        queryset = super().get_queryset()
        queryset = form.filter_memos(queryset)
        return queryset

    def get_context_data(self):
        context = super().get_context_data()
        context['search_form'] = MemoSearchForm(self.request.GET)
        return context


class MemoDetail(DetailView):
    model = Memo
    template_name = 'memo/detail.html'


class MemoCreate(CreateView):
    model = Memo
    form_class = MemoForm
    template_name = 'memo/new.html'
    success_url = reverse_lazy('memo:index')


class MemoDelete(DeleteView):
    model = Memo
    template_name = 'memo/delete.html'
    success_url = reverse_lazy('memo:index')


class MemoUpdate(UpdateView):
    model = Memo
    form_class = MemoForm
    template_name = 'memo/edit.html'
    success_url = reverse_lazy('memo:index')


class MemoListAPI(ListAPIView):
    queryset = Memo.objects.all()
    serializer_class = MemoListSerializer


class MemoRetirieveAPI(RetrieveAPIView):
    queryset = Memo.objects.all()
    serializer_class = MemoRetrieveSerializer
    lookup_field = 'slug'


class MemoCreateAPI(CreateAPIView):
    queryset = Memo.objects.all()
    serializer_class = MemoCreateSerializer


class MemoUpdateAPI(UpdateAPIView):
    queryset = Memo.objects.all()
    serializer_class = MemoUpdateSerializer
    lookup_field = 'slug'


class MemoDestroyAPI(DestroyAPIView):
    queryset = Memo.objects.all()
    serializer_class = MemoDestroySerializer
    lookup_field = 'slug'

templates/memo/base.html
<!DOCTYPE html>

<html lang="ja">

{% load static %}



    <head>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>DjangoBrosMemo</title>

    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'memo/css/style.css' %}">


    </head>



    <body>


    <h1 class="mb-5">DjangoBrosMemo</h1>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    {% bootstrap_javascript jquery='full' %}


    </body>



</html>

templates/memo/delete.html
{% extends 'memo/base.html' %}

templates/memo/detail.html
{% extends 'memo/base.html' %}

{% block content %}

<div class="my-5">
    <a href="{% url 'memo:index' %}">ホームに戻る</a>
</div>
  
<h2 class="my-3">{{ memo.title }}</h2>
<div class="my-3">
    {{ memo.text | linebreaks | urlize }}
</div>

<form method="post" action="{% url 'memo:delete_memo' memo.slug %}">
    {% csrf_token %}
    <a class="btn" href="{% url 'memo:edit_memo' memo.slug %}">編集</a>
    <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
</form>

{% endblock content %}

templates/memo/edit.html
{% extends 'memo/base.html' %}

{% block content %}

<div class="my-5">
    <a href="{% url 'memo:detail' memo.slug %}">戻る</a>
</div>

<form action="{% url 'memo:edit_memo' memo.slug %}" method="POST">
    {% csrf_token %}

    {% if form.non_field_errors %}
    <div class="error-list text-danger font-weight-bold">
    {% for error in form.non_field_errors %}
        {{ error }}<br>
    {% endfor %}
    </div>
    {% endif %}

    <table  class="table table-borderless my-3">
        {% for field in form %}
        <tr>
            <th>{{ field.label }}</th>
            <td>
                {{ field }}
                {% if field.errors %}
                <div class="error-list text-danger font-weight-bold">
                    {% for error in field.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>

    <button class="btn" type="submit">保存</button>

</form>

{% endblock content %}

templates/memo/includes/paginator.html
{% load memo_tags %}

<nav aria-label="Page navigation" class="my-5">

  <ul class="pagination justify-content-center">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
    
  </ul>

</nav>

templates/memo/index.html
{% extends 'memo/base.html' %}

{% block content %}

<form action="" class="form-inline my-2 my-lg-0 float-right">

  {% if search_form.non_field_errors %}
  <div class="error-list text-danger font-weight-bold">
    {% for error in search_form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
  {% endif %}

  {% for field in search_form %}
  <div class="form-group">
    {{ field.label_tag }}
    {{ field }}
    {% if field.errors %}
    <div class="error-list text-danger font-weight-bold">
      {% for error in field.errors %}
        {{ error }}
      {% endfor %}
    </div>
    {% endif %}
  </div>
  {% endfor %}

  <button type="submit" class="btn my-2 my-sm-0">検索</button>

</form>

<div class="my-5">
  <a class="btn" href="{% url 'memo:new_memo' %}">新規メモ作成</a>
</div>

{% for memo in memo_list %}
<a href="{% url 'memo:detail' memo.slug %}" class="memo-title">
  <div>
    {{ memo }}
    <span class="updated_datetime">{{ memo.updated_datetime }}</span>
  </div>
</a>
{% empty %}
<p>表示するメモがありません。</p>
{% endfor %}

{% include 'memo/includes/paginator.html' %}

{% endblock content %}

templates/memo/new.html
{% extends 'memo/base.html' %}

{% block content %}

<div class="my-5">
    <a href="{% url 'memo:index' %}">ホームに戻る</a>
</div>

<form action="{% url 'memo:new_memo' %}" method="POST">
    {% csrf_token %}

    {% if form.non_field_errors %}
    <div class="error-list text-danger font-weight-bold">
    {% for error in search_form.non_field_errors %}
        {{ error }}<br>
    {% endfor %}
    </div>
    {% endif %}

    {% for field in form %}
    <div class="form-group">
    {{ field.label_tag }}
    {{ field }}
    {% if field.errors %}
    <div class="error-list text-danger font-weight-bold">
        {% for error in field.errors %}
            {{ error }}<br>
        {% endfor %}
    </div>
    {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn">保存</button>

</form>

{% endblock content %}